[Design] L2 state derived automatic contract update transactions.
ten-protocol/go-ten pull request #1736
Opened 2024-01-07 19:58 UTC by StefanIliev545

### Why this change is needed

Please provide a description and a link to the underlying ticket

### What changes were made as part of this PR

Please provide a high level list of the changes made

### PR checks pre-merging

Please indicate below by ticking the checkbox that you have read and performed the required
[PR checks](https://github.com/ten-protocol/ten-internal/blob/main/dev-ops-docs/dev-pr-checks.md)

- [ ] PR checks reviewed and performed

2024-01-08 10:18 UTC, BedrockSquirrel commented
This feels like a cool, pretty unique feature if we could pull it off.

Having to regularly update state as an admin function seems pretty common, I think games developers would find that useful (as well as the AMMs etc. you mentioned).



My first thought was DOS attack vector, which you addressed, but I'm a bit worried that the number of these checks will grow and grow like a memory leak.

I'm not sure the one-off cost is going to cut it for that, because these auto-update contracts will live forever unless users deregister them I guess, and there's no incentive to deregister really (if the checkUpdate function is free and it's always false because their dapp is dead or whatever so they're not being charged for it actually executing).

I was wondering, would it be possible to have the developer deposit eth that will be used to pay for the auto-update check functions? This would mean that:
- we could scrap the hard cap on the gas, more flexible for them
- there is an ongoing cost even if the result is always false, so DOS attack more expensive
- if the dev abandons the project their deposit will eventually run out and the auto-update contract would be frozen so that it doesn't cost our nodes CPU time forever

What do you reckon? Not sure how hard it would be to implement.

2024-01-08 10:22 UTC, BedrockSquirrel commented
"I imagine this would be really great for automated arbitrage" is a cool point, acknowledging that 'good' MEV exists on the chain and needs to be mopped up.

I think publicising this feature would be really important because like you said it's non-standard so people won't expect it. But app developers that want automated housekeeping functions and people wanting to hunt MEV is a pretty big market to pitch it to imo.

I think it's important in the long term that we don't make it too cheap though, it's going to cost us to run these and this could be a way to monetise the chain to keep gas fees low, if we can indirectly claim a slice of the MEV by allowing people to register their on-chain algos.

2024-01-11 15:42 UTC, tudor-malene requested changes
The design needs a bit of restructuring to make it more clear.
Start with the high level, then the use cases, then the proposed implementation.

Is there any usage for gaming that you can think of?

2024-01-11 15:42 UTC, tudor-malene commented on design/scratchpad/Design_auto_updater.md
> +## Introduction
It is not clear what high-level problem this solves

2025-02-17 08:22 UTC, StefanIliev545 commented
The system contract for callbacks provides this.

2025-02-17 08:22 UTC, closed without merging