Ziga/add personal sign authentication message
ten-protocol/go-ten pull request #1811
Opened 2024-02-21 11:38 UTC by zkokelj

### Why this change is needed

We want to use Rainbowkit (https://www.rainbowkit.com/) in the future and they don't support EIP-712 messages yet.
To use them we need to add personal sign message, because it is impossible to overwrite signer there.

### What changes were made as part of this PR

- Added new personal sign message and methods to verify it.
- Refactored code around verifying signatures

### PR checks pre-merging

Please indicate below by ticking the checkbox that you have read and performed the required
[PR checks](https://github.com/ten-protocol/ten-internal/blob/main/dev-ops-docs/dev-pr-checks.md)

- [ ] PR checks reviewed and performed

2024-02-26 16:30 UTC, tudor-malene requested changes

2024-02-26 16:30 UTC, tudor-malene commented on go/common/viewingkey/viewing_key.go
> +func CheckIfSignatureIsValidAndMatchesAddress(encryptionToken string, signature []byte, chainID int64, expectedAddress *gethcommon.Address) bool {
this approach is not great.
Let's add a "type int" field in the "RPCSignedViewingKey".
The type will be an iota of either "EIP712" or "Personal".

Based on that type, you choose the signature verification method

2024-03-14 10:10 UTC, tudor-malene reviewed
thanks Ziga. Much better now.
A few improvements and this should be good to merge

2024-03-14 10:37 UTC, zkokelj commented on go/common/viewingkey/viewing_key.go
> +type SignatureType string
This was my initial approach, but having `SignatureType` of type `int`  causes problems with RLP serialisation. 
And errors like this:
```
Cause: rlp: type int is not RLP-serializable (struct field viewingkey.RPCSignedViewingKey.SignatureType) (struct field common.LogSubscription.ViewingKey)"}} component=test_log
```

2024-03-14 15:07 UTC, zkokelj commented on tools/walletextension/lib/client_lib.go
> +	prefixedMessage := fmt.Sprintf(viewingkey.PersonalSignMessagePrefix, len(personalSignMessage), personalSignMessage)
Good point. Actually this prefixing can be removed by using `accounts.TextHash` from geth, which adds the prefix and hashes the message + keeping it without a prefix is better for the new endpoints (wallets like Metamask automatically adds this prefix to the message)

2024-03-14 15:32 UTC, zkokelj commented on go/common/viewingkey/viewing_key.go
> +	} else if signatureType == EIP712Signature {
fixed.

2024-03-14 15:33 UTC, zkokelj commented on go/common/viewingkey/viewing_key.go
> +// checkEIP712Signature checks if signature is valid for provided userID and chainID and return address or nil if not valid
fixed

2024-03-14 16:01 UTC, zkokelj commented
General comment / question.

Is it critical if our system is vulnerable to the following (possible attack)?

When users sign the message to authenticate them they have 3 options (legacy will be removed and I won't talk about it).
 `personalSign` and  `EIP712Sign`. This is used to prove, that they are actually the owners of that account.
But if user sends the signature to the node and sets the message type to the other type the node "thinks" that it is another address and does not detect that. To be able to detect that we would need to include messageHash with the signature. 
What do you think @tudor-malene ?

2024-03-15 09:48 UTC, tudor-malene commented
> General comment / question.
> 
> Is it critical if our system is vulnerable to the following (possible attack)?
> 
> When users sign the message to authenticate them they have 3 options (legacy will be removed and I won't talk about it). `personalSign` and `EIP712Sign`. This is used to prove, that they are actually the owners of that account. But if user sends the signature to the node and sets the message type to the other type the node "thinks" that it is another address and does not detect that. To be able to detect that we would need to include messageHash with the signature. What do you think @tudor-malene ?

If I understand the attack correctly, the user wants to read the data of an account they don't control. For this, they have to produce a signed message of one of the 2 formats that contains the target address in the right place and sign that with a key they control that somehow, when going through our recovery algorithm will produce the right values?

2024-03-15 09:54 UTC, tudor-malene reviewed
thanks Ziga. I think it looks good now. The responsibilities are quite clear.
One last thing to check if other int data types work for the type .

2024-03-15 09:54 UTC, tudor-malene commented on go/common/viewingkey/viewing_key.go
> +type SignatureType string
what about int8 or one of the other int types?

2024-03-15 09:54 UTC, tudor-malene commented on go/common/viewingkey/viewing_key.go
> +// SignatureChecker is an interface for checking if signature is valid for provided encryptionToken and chainID and return address or nil if not valid
return "signing address"

2024-03-15 11:49 UTC, zkokelj commented on go/common/viewingkey/viewing_key.go
> +type SignatureType string
all int types fail with the same error unfortunately

2024-03-15 11:53 UTC, tudor-malene commented on go/common/viewingkey/viewing_key.go
> +type SignatureType string
what about uints?

2024-03-18 10:48 UTC, tudor-malene approved these changes
lgtm

2024-03-18 11:09 UTC, merged