WIP EOA system contract upgrader
ten-protocol/go-ten pull request #2150
Opened 2024-11-20 14:34 UTC by StefanIliev545

### Why this change is needed

Please provide a description and a link to the underlying ticket

### What changes were made as part of this PR

Please provide a high level list of the changes made

### PR checks pre-merging

Please indicate below by ticking the checkbox that you have read and performed the required
[PR checks](https://github.com/ten-protocol/ten-internal/blob/main/dev-ops-docs/dev-pr-checks.md)

- [ ] PR checks reviewed and performed

2024-11-20 15:06 UTC, tudor-malene commented on go/enclave/storage/init/sqlite/001_init.sql
> +    is_synthetic   boolean    NOT NULL
something is weird here. One change was made to the edgless file and one to the sqlite one

2024-11-21 14:09 UTC, StefanIliev545 commented on go/enclave/components/interfaces.go
> +	ExecuteBatch(context.Context, *core.Batch) ([]*core.TxExecResult, []*core.SyntheticTx, error)
Good question, I dunno

2024-11-22 10:09 UTC, StefanIliev545 commented on go/enclave/components/interfaces.go
> +	ExecuteBatch(context.Context, *core.Batch) ([]*core.TxExecResult, []*core.SyntheticTx, error)
On second attempt it looks a bit cleaner this way; otherwise we have to filter them out of the exec results. Unless I'm misunderstanding?

2024-11-22 11:43 UTC, tudor-malene requested changes
few comments to keep the logic uniform

2024-11-25 12:31 UTC, tudor-malene commented
> ### Why this change is needed
> Please provide a description and a link to the underlying ticket
> 
> ### What changes were made as part of this PR
> Please provide a high level list of the changes made
> 
> ### PR checks pre-merging
> Please indicate below by ticking the checkbox that you have read and performed the required [PR checks](https://github.com/ten-protocol/ten-internal/blob/main/dev-ops-docs/dev-pr-checks.md)
> 
> * [ ]  PR checks reviewed and performed

Description, pls

2024-11-25 12:45 UTC, tudor-malene approved these changes
LGTM

2024-11-26 09:01 UTC, merged